# Taller 1

### Andrés David Campos

### 201413737

In [2]:
import os
import pandas as pd
%pylab inline

Populating the interactive namespace from numpy and matplotlib

### Se importan las librerias que seran utilizadas en el desarrollo de este taller.

In [3]:
def nrelYideam(ciudad):
    base_dir = os.path.join( '/home/nbuser/library/Semana 3/data')
    output_dir = os.path.join( '.','output')
    fuenteIDEAM = 'IDEAM'
    serie_csv1 = os.path.join(base_dir,ciudad,fuenteIDEAM+'.csv')
    serie_ideam = pd.read_csv(serie_csv1, sep = ';',
                encoding='latin-1')
    fuenteNREL = 'NREL'
    serie_csv2 = os.path.join(base_dir,ciudad,fuenteNREL+'.csv')
    serie_NREL = pd.read_csv(serie_csv2, sep = ';',
                encoding='latin-1')
    
    return serie_NREL, serie_ideam

### Esta función recoge los datos que se encuentran en la carpeta "data".
 
 * Parametro: string de la ciudad
 * Retorna: la serie NREL y la IDEAM de la ciudad

In [4]:
def ghi_mensual(serie_horaria):
    agnos = sorted(serie_horaria['AÑO'].unique())
    ghi_df = pd.DataFrame(columns=["AÑO", "MES", "DIAS", "GHImes"])
    
    for agno in agnos:
        for mes in range(1,13):
            nombre_energia = list(serie_horaria)[-1]
            
            dias = sorted(serie_horaria[(serie_horaria['AÑO'] == agno) &
                        (serie_horaria['MES'] == mes)]["DIA"].unique())
            
            ghi_mes = serie_horaria.loc[((serie_horaria["AÑO"] == agno)
                            & (serie_horaria["MES"] == mes)),
                                        nombre_energia].sum()/1000
            
            ghi_dict = {"AÑO":agno, "MES":mes, "DIAS":dias[-1],
                        "GHImes":ghi_mes}
            
            ghi_df = ghi_df.append(ghi_dict, ignore_index=True)
    return ghi_df

### Esta función calcula el total de energía mensual a traves de los años

* Parametros: serie horaria
* Retorna: serie con el total de energía de cada mes

In [5]:
def ghi_dia(serie_ghi_mensual):
    agnos = sorted(serie_ghi_mensual['AÑO'].unique())
    ghi_df = pd.DataFrame(columns=["AÑO", "MES", "GHIdiario"])
    
    for agno in agnos:
        for mes in range(1,13):
            dias = serie_ghi_mensual.loc[((serie_ghi_mensual["AÑO"] == agno)
                            & (serie_ghi_mensual["MES"] == mes))
                                         ,"DIAS"].item()
            
            ghi_diario = serie_ghi_mensual.loc[(
                (serie_ghi_mensual["AÑO"] == agno)
                            & (serie_ghi_mensual["MES"] == mes)),
                "GHImes"].item()/dias
            
            ghi_dict = {"AÑO":agno, "MES":mes, "GHIdiario":ghi_diario}
            
            ghi_df = ghi_df.append(ghi_dict, ignore_index=True)
    return ghi_df

### Esta función calcula el promedio de energía diario de cada mes a traves de los años

* Parametros: serie mensual
* Retorna: serie con el ppromedio de energía diario de cada mes

In [56]:
def promDiario(serie_ideam):
    ghiMensual=ghi_mensual(serie_ideam)
    ghiDiario=ghi_dia(ghiMensual)
    datos=sorted(ghiDiario['GHIdiario'])
    return datos

### Esta función realiza el procedimiento de sacar el promedio de energía diario y ordenarlo de menor a mayor en un arreglo
* Parametros: serie (ideam)
* Retorna: arreglo con los promedios de energía diarios

In [7]:
def promYdesv(serie):
    return np.mean(serie), np.std(serie)

### Esta función calcula el promedio y la desviación estandar poblacional de una serie
* Parametros: serie
* Retorna: promedio de la serie, desviación estandar poblacional de la serie

In [8]:
def MCP(serie_aCorregir, serie_modelo):
    mu_y, desv_y = promYdesv(serie_modelo)
    mu_x, desv_x= promYdesv(serie_aCorregir)
    f = ((mu_y-(desv_y/desv_x)*mu_x)+(desv_y/desv_x))*serie_aCorregir
    
    return f

In [50]:
nrel, ideam= nrelYideam('Valledupar')
x= np.array(promDiario(nrel))
y= np.array(promDiario(ideam))

In [10]:
b= MCP(y, x)

In [59]:
def seriePartida(serieP, añoInicio, añoFin, mesInicio, mesFin):
        if(añoInicio == añoFin) & (mesFin >= mesInicio):
            serie = serieP[(serieP['AÑO']==añoInicio) & (serieP['MES']>=mesInicio) & (serieP['MES']<=mesFin)]
        if(añoInicio != añoFin)
            serie = serieP[(serieP['AÑO']==añoInicio) & (serieP['MES']>=mesInicio)]
            
        return serie

In [60]:
seriePartida(ideam, 2009, 2009, 3, 10)

        AÑO  MES  DIA  HORA       IDEAM
27720  2009    3    1     0    0.000000
27721  2009    3    1     1    0.000000
27722  2009    3    1     2    0.000000
27723  2009    3    1     3    0.000000
27724  2009    3    1     4    0.000000
27725  2009    3    1     5    0.000000
27726  2009    3    1     6    0.000000
27727  2009    3    1     7   27.706167
27728  2009    3    1     8  110.824669
27729  2009    3    1     9  452.889274
27730  2009    3    1    10  658.554285
27731  2009    3    1    11  803.478852
27732  2009    3    1    12  866.350540
27733  2009    3    1    13  865.284918
27734  2009    3    1    14  803.478852
27735  2009    3    1    15  659.619907
27736  2009    3    1    16  483.792306
27737  2009    3    1    17  257.880481
27738  2009    3    1    18   35.165520
27739  2009    3    1    19    0.000000
27740  2009    3    1    20    0.000000
27741  2009    3    1    21    0.000000
27742  2009    3    1    22    0.000000
27743  2009    3    1    23    0.000000
27744  2009    3    2     0    0.000000
27745  2009    3    2     1    0.000000
27746  2009    3    2     2    0.000000
27747  2009    3    2     3    0.000000
27748  2009    3    2     4    0.000000
27749  2009    3    2     5    0.000000
...     ...  ...  ...   ...         ...
33570  2009   10   30    18    0.000000
33571  2009   10   30    19    0.000000
33572  2009   10   30    20    0.000000
33573  2009   10   30    21    0.000000
33574  2009   10   30    22    0.000000
33575  2009   10   30    23    0.000000
33576  2009   10   31     0    0.000000
33577  2009   10   31     1    0.000000
33578  2009   10   31     2    0.000000
33579  2009   10   31     3    0.000000
33580  2009   10   31     4    0.000000
33581  2009   10   31     5    0.000000
33582  2009   10   31     6    0.000000
33583  2009   10   31     7  102.299695
33584  2009   10   31     8  225.911826
33585  2009   10   31     9  460.348626
33586  2009   10   31    10  639.373092
33587  2009   10   31    11  764.050845
33588  2009   10   31    12  822.660045
33589  2009   10   31    13  485.923550
33590  2009   10   31    14  312.227193
33591  2009   10   31    15  342.064604
33592  2009   10   31    16  119.349644
33593  2009   10   31    17   43.690495
33594  2009   10   31    18    7.596707
33595  2009   10   31    19    0.000000
33596  2009   10   31    20    0.000000
33597  2009   10   31    21    0.000000
33598  2009   10   31    22    0.000000
33599  2009   10   31    23    0.000000

[5880 rows x 5 columns]